config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root :to => "users#show"
  end
  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy'
  end

  get '/rules', to: 'static_pages#rules'
  get '/contact', to: 'static_pages#contact'
  get '/privacy', to: 'static_pages#privacy'

  resources :users, only: :show

  resources :schools, only: :show

  resources :leagues do
    get 'leaderboard'
    get 'bracket'
    get 'draft_room'
    get 'points_board'
    get 'new_invite'
    get 'draft_results'
    post 'invite'
    resources :owners
  end

  resources :games, only: :update do
    patch :update_time
  end
  get '/admin_games' => 'games#admin_games', as: :admin_games

  resources :owner_schools, only: %i(create destroy)

  namespace :api, defaults: { format: :json } do
    resources :users

    resources :schools do
      collection do
        get 'bracket'
      end
    end

    resources :leagues do
      get 'draft_room'
      resources :owners
    end

    resources :owner_schools, only: %i(create destroy)
  end
end

app/models/league.rb
class League < ApplicationRecord
  validates :name, presence: true
  validate :not_too_many_owners

  belongs_to :commissioner, class_name: 'User'
  has_many :owners, dependent: :destroy
  has_many :users, through: :owners

  has_many :owner_schools, dependent: :destroy
  has_many :schools, through: :owner_schools

  before_save :set_year

  attr_accessor :invite_emails

  MAX_OWNERS = 8

  def self.current
    where(year: Time.now.year)
  end

  def self.old
    where('year < ?', Time.now.year)
  end

  def current?
    year == Time.now.year
  end

  def full?
    owners.count == MAX_OWNERS
  end

  def drafted?
    owner_schools.count == 64
  end

  def drafting?
    School.bracket_announced?(year) &&
      full? && !drafted?
  end


  def turn_for?(owner)
    return false unless owner && owner.draft_pick

    owner = owner.draft_pick
    league = current_draft_pick

    (0...4).to_a.map do |cycle|
      start = cycle * 16

      start + owner == league ||
      (start + 17) - owner == league
    end.any?
  end

  def show_has_paid?
    owners.any?(&:has_paid)
  end

  private

  def not_too_many_owners
    return unless owners.count > MAX_OWNERS
    errors.add(:owners, 'Too many owners!')
  end

  private

  def set_year
    self.year = Time.now.year unless year
  end
end

app/controllers/api/leagues_controller.rb
class Api::LeaguesController < ApplicationController
  before_action :get_league

  def draft_room
    @current_owner = current_user.owner_for(@league)
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :get_league, except: %i(index new create)
  before_action :check_if_in_league, except: %i(index new create)

  def index
    @leagues = League.all.order(created_at: :desc).select do |league|
      !league.full? && !current_user.leagues.include?(league)
    end
  end

  def new
    @league = League.new
  end

  def create
    @league = League.new(league_params)

    if @league.save
      flash[:notice] = 'League successfully created!'
      redirect_to new_league_owner_path(league_id: @league.id)
    else
      flash[:errors] = @league.errors.full_messages.join(', ')
      render :new
    end
  end

  def leaderboard
    @owners = @league.owners.sort
  end

  def bracket
    # Just show games from this league's tournament
    @games = Game.from_year(@league.year)
  end

  def draft_room
  end

  def draft_results
    @owner_schools = @league.owner_schools.includes(:owner, :school).order(:draft_pick)
  end

  def points_board
  end

  def new_invite
  end

  def invite
    if params[:league][:invite_emails].present?
      emails = params[:league][:invite_emails].split(/[\s,\n\r]/)

      emails.each do |email|
        # get rid of spaces
        email.gsub!(' ', '')
        next unless email.present? && /.@./.match(email)

        send_invite(email)
      end

      flash[:notice] = 'Invites sent.' unless emails.empty?
    end

    redirect_to league_leaderboard_path(@league)
  end

  private

  def send_invite(email)
    User.invite!(email: email)
  end

  def league_params
    params.
      require(:league).permit(:name, :description, :commissioner_id, :password)
  end
end

app/views/leagues/_bracket_game.html.erb
<li title="<%= game.id %>-top"
    class="game game-top <%= 'winner' if game.winner?(game.school1) %>">
  <% if game.school1 %>
    <%= link_to game.school1.try(:full_name_and_seed), school_url(game.school1_id) %>
  <% end %>
  <span><%= game.school1_score %></span>
</li>

<li class="game game-spacer">&nbsp;</li>

<li title="<%= game.id %>-bottom"
    class="game game-bottom <%= 'winner' if game.winner?(game.school2) %>'">
  <% if game.school2 %>
    <%= link_to game.school2.try(:full_name_and_seed), school_url(game.school2_id) %>
  <% end %>
  <span><%= game.school2_score %></span>
</li>
<li class="spacer">&nbsp;</li>

app/views/leagues/_centered_nav.html.erb
<ul id="centered-nav" class="geometric-font nav-tabs nav nav-justified">
  <li class="<%= action_name == 'leaderboard' ? 'active' : '' %>">
    <%= link_to 'Leaderboard', league_leaderboard_path(league) %>
  </li>
  <li class="<%= action_name == 'bracket' ? 'active' : '' %>">
    <%= link_to 'Bracket', league_bracket_path(league) %>
  </li>
  <li class="<%= action_name == 'draft_room' ? 'active' : '' %>">
    <%= link_to 'Draft Room', league_draft_room_path(league) %>
  </li>
</ul>

app/views/leagues/_header.html.erb
<h2><%= league.name %></h2>
<h4><%= league.description %></h4>

<div class="full-reminder">
  <% if league.full? %>
    Congrats! Your league is full and ready to rumble.
  <% else %>
    <p>
      Your league is still
      <strong><%= pluralize(8 - league.owners.count, 'owner') %></strong>
      away from being ready to participate.
    </p>
    <p>
      <strong>Reminder:</strong> You have until 11:59 PT Wednesday, March 17 to have 8 owners.
    </p>
    </br>
    <p>Invite your friends by giving them the League's name and password:</p>
    <p>League Name: <strong><%= league.name %></strong></p>
    <p>League Password: <strong><%= league.password %></strong></p>

    <%#TODO: link_to 'Invite Friends to this League', league_new_invite_path(league), class: 'btn btn-primary' %>
  <% end %>
</div>

</br>

<%= render 'leagues/league_nav', league: league %>

app/views/leagues/_league_nav.html.erb
<ul id="centered-nav" class="nav-tabs nav nav-justified">
  <li class="<%= action_name == 'leaderboard' ? 'active' : '' %>">
    <%= link_to 'Leaderboard', league_leaderboard_path(league) %>
  </li>

  <li class="<%= my_owner_page? ? 'active' : '' %>">
    <%= link_to 'My Squad', league_owner_path(league, current_user.owner_for(league)) %>
  </li>

  <li class="<%= action_name == 'bracket' ? 'active' : '' %>">
    <%= link_to 'Bracket', league_bracket_path(league) %>
  </li>

  <% if league.current? && !league.drafted? && School.bracket_announced?(league.year) %>
    <li class="<%= action_name == 'draft_room' ? 'active' : '' %>">
      <%= link_to 'Draft Room', league_draft_room_path(league) %>
    </li>
  <% end %>

  <li class="<%= action_name == 'points_board' ? 'active' : '' %>">
    <%= link_to 'Points Board', league_points_board_path(league) %>
  </li>

  <li class="<%= action_name == 'draft_results' ? 'active' : '' %>">
    <%= link_to 'Draft Results', league_draft_results_path(league) %>
  </li>
</ul>

app/views/leagues/_user_data.html.erb
<script type='text/javascript'>
    window.dm = window.dm || {};
    window.dm.userData = <%= user_data.to_json.html_safe %>;
</script>

app/views/leagues/bracket.html.erb
<%= render 'header', league: @league %>

<main id="bracket">
  <% if School.bracket_announced?(Time.now.year) && @league.current? %>
    <% current_round_games = @games.where(round: 0).order(:id) %>

    <% 6.times do |round_num| %>
      <% next_round_games = [] %>

      <ul class="round round-<%= round_num %>">
        <li class="spacer">&nbsp;</li>

        <% current_round_games.each_with_index do |game, idx| %>
          <%= render 'bracket_game', game: game %>
          <% next_round_games << game.next_game if idx.odd? && game.next_game %>
        <% end %>

        <% current_round_games = next_round_games %>
      </ul>
    <% end %>

  <% elsif @league.year == 2016 %>
    <%= image_tag '2016-bracket-ncaa', id: 'bracket-2016' %>
  <% else %>
    <h4 class="text-center">
      The bracket will be posted here shortly after it has been released. Check back soon!
    </h4>
  <% end %>
</main>

app/views/leagues/draft_results.html.erb
<%= render 'header', league: @league %>

<div class="section">

  <h3 class="text-center">Draft Results</h3>

  <table class="draft-results table table-responsive table-hover table-condensed">
    <tr class="active">
      <th>Round</th>
      <th>Pick</th>
      <th>Owner</th>
      <th>School</th>
      <th>Region</th>
      <th>Seed</th>
      <th>Total Points</th>
    </tr>
    <% @owner_schools.each do |os| %>
      <tr class="<%= os.school.wins_count_class %> <%= os.school.alive? ? 'alive' : '' %>">
        <td><%= os.draft_round %></td>
        <td><%= os.draft_pick %></td>
        <td title="<%= os.owner.user.email %>"><%= link_to os.owner.team_name, league_owner_path(@league, os.owner) %></td>
        <td><%= link_to os.school.full_name, school_path(os.school) %></td>
        <td><%= os.school.seed_number %></td>
        <td><%= os.school.region %></td>
        <td><%= os.school.total_points %></td>
      </tr>
    <% end %>
  </table>

  </br>
  <div class="draft-results-key">
    <h4 class="text-center">Key</h4>
    <table class="draft-results table table-responsive table-condensed">
      <tr class="champ alive">
        <td><%= Date.today.year %> National Champion</td>
      </tr>
      <tr class="title-gamer alive">
        <td>Finalist</td>
      </tr>
      <tr class="final-four alive">
        <td>Final Four</td>
      </tr>
      <tr class="elite alive">
        <td>Elite Eight</td>
      </tr>
      <tr class="sweet alive">
        <td>Sweet Sixteen</td>
      </tr>
      <tr class="one-win alive">
        <td>Round of 32</td>
      </tr>
      <tr class="no-wins">
        <td>Thanks for coming</td>
      </tr>
    </table>
    <p><strong>Still Alive</strong> / Knocked Out</p>
  </div>
</div>

app/views/leagues/draft_room.html.erb
<%= render 'header', league: @league %>

<h3 class="text-center">Welcome to the Draft Room</h3>

<% if @league.full? %>
  <div id="draft-room-container"></div>
  <%= javascript_pack_tag 'DraftReact' %>
<% else %>
  <h4 class="text-center">
    The draft has not yet begun because your league still does not have the required 8 owners.
  </h4>
<% end %>

app/views/leagues/index.html.erb
<% if @leagues.any? %>
  <h3>Available Leagues</h3>

  <table class="table table table-hover">
    <tr>
      <th>League Name</th>
      <th>Created At</th>
      <th>Number of Owners</th>
      <th></th>
    </tr>
    <% @leagues.each do |league| %>
      <tr>
        <td><%= league.name %></td>
        <td><%= league.created_at.strftime('%b. %-d, %l:%M%P') %></td>
        <td><%= league.owners.count %></td>
        <td><%= link_to 'Join League?', new_league_owner_path(league) %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <h3>There are no available leagues for you to join.</h3>
  <%= link_to 'Create Your Own League', new_league_path, class: 'btn btn-primary' %>
  <%= link_to 'Back to your Homepage', user_path(current_user), class: 'btn btn-default' %>
<% end %>

app/views/leagues/leaderboard.html.erb
<%= render 'header', league: @league %>

<% cache("league:#{@league.id}:leaderboard", expires_in: 5.minutes) do %>

  <div class="row">
    <table class="table table-responsive table-hover table-condensed">
      <tr class="active">
        <th>Ranking</th>
        <% if @league.show_has_paid? %>
          <th>Paid?</th>
        <% end %>
        <th>Owner Name</th>
        <th>Schools Left</th>
        <% 6.times do |round| %>
          <th><%= Game::ROUND_NAMES[round] %></th>
        <% end %>
        <th title="Points Possible Remaining">PPR*</th>
        <th>Max</th>
        <th>TOTAL</th>
      </tr>
      <% @owners.each_with_index do |owner, idx| %>
        <tr>
          <th><%= idx + 1 %></th>
          <% if @league.show_has_paid? %>
            <th>
              <% if owner.has_paid %>
                <i class="fas fa-dollar-sign"></i>
              <% end %>
            </th>
          <% end %>
          <th title="<%= owner.user.email %>">
            <%= link_to owner.team_name, league_owner_path(@league, owner) %>
          </th>
          <td><%= owner.schools_left_count %></td>
          <% 6.times do |round| %>
            <td><%= owner.score_for_round(round) %></td>
          <% end %>
          <td><%= owner.ppr %></td>
          <td><%= owner.max %></td>
          <th><%= owner.total_points %></th>
        </tr>
      <% end %>
      <tr>
        <td></td>
        <% if @league.show_has_paid? %>
          <td></td>
        <% end %>
        <td></td>
        <th><%= School.left_alive_count(@league.year) %></th>
        <% 9.times do %>
          <td></td>
        <% end %>
      </tr>
    </table>
    <em class="pull-right">*Points Possible Remaining</em>
  </div>

<% end %>

app/views/leagues/new.html.erb
<h2>Create a New League</h2>

<%= simple_form_for :league, url: leagues_url, html: { class: 'form-vertical' } do |f| %>

  <%= f.input :name, label: 'League Name', html: { maxlength: 255 } %>
  </br>

  <%= f.input :description, as: :text, label: 'Description', input_html: { cols: 50 },
    required: false, placeholder: "There's no crying in basketball." %>
  </br>

  <%= f.input :password, as: :string, required: false,
    input_html: { 'aria-describedly' => 'helpBlock'} %>

  <span class="help-block">
    Create a password to give out to other users, so that only they can join your league.
  </span>
  </br>

  <%= f.hidden_field :commissioner_id, value: current_user.id %>

  <%= f.button :submit, 'Create League!', class: 'btn btn-primary' %>
<% end %>

<span class="help-block">
  <strong>Hail to the chief!</strong>
  Since you are creating this League, you will be deemed its commissioner.
</span>

app/views/leagues/new_invite.html.erb
<h2>Invite Friends to <%= @league.name %></h2>


<%= simple_form_for :league, url: league_invite_url(@league), html: { class: 'form-vertical' } do |f| %>
  <%= f.input :invite_emails, as: :text, label: 'Description', input_html: { cols: 50 },
    placeholder: "john.wooden@ucla.edu, carmelo@syracuse.edu" %>

  <span class="help-block">
    Type in up to 8 emails separated by commas.
  </span>
  </br>

  <%= f.button :submit, 'Send Invites', class: 'btn btn-primary' %>
<% end %>

app/views/leagues/points_board.html.erb
<%= render 'header', league: @league %>

<%= render 'shared/points' %>