config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root :to => "users#show"
  end
  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy'
  end

  get '/rules', to: 'static_pages#rules'
  get '/contact', to: 'static_pages#contact'
  get '/privacy', to: 'static_pages#privacy'

  resources :users, only: :show

  resources :schools, only: :show

  resources :leagues do
    get 'leaderboard'
    get 'bracket'
    get 'draft_room'
    get 'points_board'
    get 'new_invite'
    get 'draft_results'
    post 'invite'
    resources :owners
  end

  resources :games, only: :update do
    patch :update_time
  end
  get '/admin_games' => 'games#admin_games', as: :admin_games

  resources :owner_schools, only: %i(create destroy)

  namespace :api, defaults: { format: :json } do
    resources :users

    resources :schools do
      collection do
        get 'bracket'
      end
    end

    resources :leagues do
      get 'draft_room'
      resources :owners
    end

    resources :owner_schools, only: %i(create destroy)
  end
end

app/models/owner.rb
class Owner < ApplicationRecord
  include Comparable

  belongs_to :user
  belongs_to :league
  has_many :owner_schools
  has_many :schools, through: :owner_schools

  validates :team_name, :user, :league, presence: true
  validates :user, uniqueness: { scope: :league, message: 'you may only have one owner per league' }

  after_commit :set_draft_order, on: :create

  attr_accessor :league_password

  def self.current
    joins(:league).where('leagues.year = ?', Time.now.year)
  end

  def self.old
    joins(:league).where('leagues.year < ?', Time.now.year)
  end

  def total_points
    schools.map(&:total_points).sum.round(2)
  end

  def <=>(other)
    other.total_points - total_points
  end

  def current_ranking
    league.owners.sort.each_with_index do |owner, idx|
      next unless owner.id == id
      return idx + 1
    end
  end

  def score_for_round(round)
    schools.map do |school|
      school.score_for_round(round)
    end.sum.round(2)
  end

  def ppr
    schools.map(&:ppr).sum.round(2)
  end

  def max
    schools.map(&:max).sum.round(2)
  end

  def pick_for(school)
    owner_schools.find_by(school: school).draft_pick
  end

  def commissioner?
    league.commissioner == user
  end

  def set_draft_order
    return unless last_league_member?

    draft_picks = (1..8).to_a.shuffle
    league.owners.each_with_index do |owner, idx|
      owner.update(draft_pick: draft_picks[idx])
    end
  end

  def last_league_member?
    league.owners.count == 8
  end

  def current_turn?
    league.turn_for?(self)
  end

  def selected_regions
    schools.includes(:seed).map(&:region)
  end

  def pending_games
    schools.map(&:games).flatten.uniq.select do |game|
      !game.is_over && game.school1
    end.sort_by do |game|
      game.start_time || Time.now
    end
  end

  def completed_games
    sql = "school1_id in (?) OR school2_id in (?)"
    Game.completed_games.where(sql, school_ids, school_ids).order(:start_time).reverse
  end

  def schools_left_count
    schools.select(&:alive?).count
  end
end

app/controllers/api/owners_controller.rb
class Api::OwnersController < ApplicationController
  def index
    @league = League.find(params[:league_id])
    @owners = @league.owners.order(:draft_pick)
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :get_league
  before_action :check_if_in_league, only: :show

  def new
    @owner = @league.owners.new
  end

  def create
    @owner = @league.owners.new(owner_params)
    open_sesame = @league.password == params[:owner][:league_password]

    if open_sesame
      if @owner.save
        flash[:notice] = 'Squad successfully created!'
        redirect_to league_leaderboard_path(@owner.league)
      else
        flash[:errors] = @owner.errors.full_messages.join(', ')
        render :new
      end
    else
      flash[:errors] = 'League password was incorrect'
      render :new
    end
  end

  def edit
    @owner = Owner.find(params[:id])
  end

  def update
    @owner = Owner.find(params[:id])

    if @owner.update(owner_params)
      flash[:notice] = 'Squad successfully updated!'
      redirect_to league_owner_path(@league, @owner)
    else
      flash[:errors] = @owner.errors.full_messages.join(', ')
      render :edit
    end
  end

  def show
    @owner = Owner.find(params[:id])
    @schools = @owner.owner_schools.order(:draft_pick).map(&:school)

    @pending_games = @owner.pending_games
    @completed_games = @owner.completed_games
  end

  private

  def owner_params
    params.require(:owner).permit(:team_name, :motto, :user_id, :league_id)
  end
end

app/views/owners/_owner_stat_table.html.erb
<div class="section">
  <table class="table table-responsive table-hover table-condensed">
    <tr class="active">
      <th>Pick #</th>
      <th>School</th>
      <th>Seed</th>
      <th>Region</th>
      <% 6.times do |round| %>
        <th><%= Game::ROUND_NAMES[round] %></th>
      <% end %>
      <th title="Points Possible Remaining">PPR*</th>
      <th>Max</th>
      <th>TOTAL</th>
    </tr>
    <% schools.each do |school| %>
      <tr class="<%= 'danger' unless school.alive? %>">
        <th><%= owner.pick_for(school) %></th>
        <th><%= link_to school.full_name, school_path(school) %></th>
        <td><%= school.seed_number %></td>
        <td><%= school.region %></td>
        <% 6.times do |round| %>
          <td><%= school.score_for_round(round) %></td>
        <% end %>
        <td><%= school.ppr %></td>
        <td><%= school.max %></td>
        <th><%= school.total_points %></th>
      </tr>
    <% end %>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th>Totals:</th>
      <% 6.times do |round| %>
        <td><%= owner.score_for_round(round) %></td>
      <% end %>
      <td><%= owner.ppr %></td>
      <td><%= owner.max %></td>
      <th><%= owner.total_points %></th>
    </tr>
  </table>
  <em class="pull-right">*Points Possible Remaining</em>

  <% if current_user.id == owner.user_id && schools.empty? %>
    <p>You haven't selected any schools yet.</p>
    <% if league.drafting? %>
      <p>
        Go to the
        <%= link_to 'Draft Room', league_draft_room_path(league) %>
        to add some schools to your squad!
      </p>
    <% end %>
  <% end %>
</div>

app/views/owners/edit.html.erb
<h2>Edit Your Squad</h2>

<%= simple_form_for :owner, url: league_owner_url, method: :patch, html: { class: 'form-vertical' } do |f| %>

  <%= f.input :team_name, label: 'Name', html: { maxlength: 255 } %>
  </br>

  <%= f.input :motto, as: :text, label: 'Motto', input_html: { cols: 50 },
    required: false, placeholder: "Win or go home." %>
  </br>

  <%= f.button :submit, 'Update Info', class: 'btn btn-primary' %>
<% end %>

app/views/owners/new.html.erb
<h2>Name Your Squad for <em><%= @league.name %></em></h2>

<%= simple_form_for :owner, url: league_owners_url, html: { class: 'form-vertical' } do |f| %>

  <%= f.input :team_name, label: 'Name', html: { maxlength: 255 } %>
  </br>

  <%= f.input :motto, as: :text, label: 'Motto', input_html: { cols: 50 },
    required: false, placeholder: "Win or go home." %>
  </br>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <% if current_user.commissioner?(@league) %>
    <%= f.hidden_field :league_password, value: @league.password %>

  <% else %>
    <%= f.input :league_password %>
    <span class="help-block">
      Enter the league password for <%= @league.name %>.
    </span>
    </br>
  <% end %>

  <%= f.button :submit, 'Get to the Bracket!', class: 'btn btn-primary' %>
<% end %>

app/views/owners/show.html.erb
<%= render 'leagues/header', league: @league %>

<div class="section">
  <h2><%= @owner.team_name %></h2>
  <h4>
    <%= @owner.motto %>
    <% if @owner.user_id == current_user.id %>
      <%= link_to 'Edit Squad Info', edit_league_owner_path(@league, @owner), class: 'btn' %>
    <% end %>
  </h4>
  <h4><%= @owner.user.email %></h4>
</div>
</br>

<%= render 'owner_stat_table', owner: @owner, schools: @schools, league: @league %>

<% if @pending_games.any? %>
  <div class="row">
    <h4 class="game-header">
      Pending Games:
    </h4>
    <% @pending_games.each do |game| %>
      <%= render 'shared/game', game: game %>
    <% end %>
  </div>
<% end %>

<% if @completed_games.any? %>
  <div class="row">
    <h4 class="game-header">
      Completed Games:
    </h4>
    <% @completed_games.each do |game| %>
      <%= render 'shared/game', game: game %>
    <% end %>
  </div>
<% end %>