config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root :to => "users#show"
  end
  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy'
  end

  get '/rules', to: 'static_pages#rules'
  get '/contact', to: 'static_pages#contact'
  get '/privacy', to: 'static_pages#privacy'

  resources :users, only: :show

  resources :schools, only: :show

  resources :leagues do
    get 'leaderboard'
    get 'bracket'
    get 'draft_room'
    get 'points_board'
    get 'new_invite'
    get 'draft_results'
    post 'invite'
    resources :owners
  end

  resources :games, only: :update do
    patch :update_time
  end
  get '/admin_games' => 'games#admin_games', as: :admin_games

  resources :owner_schools, only: %i(create destroy)

  namespace :api, defaults: { format: :json } do
    resources :users

    resources :schools do
      collection do
        get 'bracket'
      end
    end

    resources :leagues do
      get 'draft_room'
      resources :owners
    end

    resources :owner_schools, only: %i(create destroy)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :validatable, :invitable

  devise :invitable, :omniauthable, omniauth_providers: [:facebook]

  validates :email, presence: true

  has_many :owners
  has_many :leagues, through: :owners
  has_many :owned_schools, through: :owners, source: :schools

  def self.from_omniauth(auth)
    user = self.find_by(email: auth.info.email)

    omniauth_params = {
      provider: auth.provider,
      uid: auth.uid,
      email: auth.info.email,
      password: Devise.friendly_token[0, 20]
    }

    if user
      user.update(omniauth_params)
    else
      user = self.create(omniauth_params)
    end

    user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def current_games
    Game.current_games.select do |game|
      school_ids.any? { |x| game.school_ids.include?(x) }
    end
  end

  def owner_for(league)
    owners.find_by(league: league)
  end

  def commissioner?(league)
    self == league.commissioner
  end

  def admin?
    is_admin
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  include Devise::Controllers::Rememberable

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      remember_me(@user)
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @owners_by_league = @user.owners.old.order(created_at: :desc)
  end
end

app/views/users/show.html.erb
<h4><%= @user.email %></h4>
</br>

<% if @user.leagues.current.any? %>
  <h3>Your Current Leagues</h3>

  <table class="table table table-hover">
    <tr>
      <th>League Name</th>
      <th>Owner Name</th>
      <th>Current Points</th>
      <th>Current Ranking</th>
    </tr>
    <% @user.owners.current.each do |owner| %>
      <tr>
        <td>
          <%= link_to owner.league.name, league_leaderboard_path(owner.league) %>
          <% if owner.league.drafting? %>
            <%= link_to league_draft_room_path(owner.league) do %>
              <strong><code>
                Drafting!
                <% if owner.current_turn? %>
                  AND IT'S YOUR TURN!
                <% end %>
              </code></strong>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to owner.team_name, league_owner_path(owner.league, owner) %></td>
        <td><%= owner.total_points %></td>
        <td><%= owner.current_ranking.presence || '-' %></td>
      </tr>
    <% end %>
  </table>

<% else %>
  <p>You have not joined any leagues yet this year! Choose one of the options below to get started:</p>
<% end %>
<%= link_to 'Create a League', new_league_path, class: 'btn btn-primary' %>
<%= link_to 'Join a League', leagues_path, class: 'btn btn-primary' %>
</br>

<% if @user.leagues.old.any? %>
  <h3>Your Old Leagues</h3>

  <table class="table table table-hover">
    <tr>
      <th>League Name</th>
      <th>Year<th>
      <th>Owner Name</th>
      <th>Points</th>
      <th>Ranking</th>
    </tr>
    <% @owners_by_league.each do |owner| %>
      <tr>
        <td><%= link_to owner.league.name, league_leaderboard_path(owner.league) %></td>
        <td><%= owner.league.year %></td>
        <td><%= link_to owner.team_name, league_owner_path(owner.league, owner) %></td>
        <td><%= owner.total_points %></td>
        <td><%= owner.current_ranking.presence || '-' %></td>
      </tr>
    <% end %>
  </table>
<% end %>