config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root :to => "users#show"
  end
  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy'
  end

  get '/rules', to: 'static_pages#rules'
  get '/contact', to: 'static_pages#contact'
  get '/privacy', to: 'static_pages#privacy'

  resources :users, only: :show

  resources :schools, only: :show

  resources :leagues do
    get 'leaderboard'
    get 'bracket'
    get 'draft_room'
    get 'points_board'
    get 'new_invite'
    get 'draft_results'
    post 'invite'
    resources :owners
  end

  resources :games, only: :update do
    patch :update_time
  end
  get '/admin_games' => 'games#admin_games', as: :admin_games

  resources :owner_schools, only: %i(create destroy)

  namespace :api, defaults: { format: :json } do
    resources :users

    resources :schools do
      collection do
        get 'bracket'
      end
    end

    resources :leagues do
      get 'draft_room'
      resources :owners
    end

    resources :owner_schools, only: %i(create destroy)
  end
end

app/views/shared/_fb_sdk.html.erb
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '1574031672920275',
      xfbml      : true,
      version    : 'v2.5'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

app/views/shared/_flash_notifications.html.erb
<div class="flash-messages">
  <% flash.each do |key, message| %>
    <% css_class = key %>
    <% css_class = 'danger' if %w(alert error errors).include?(key) %>
    <% css_class = 'success' if key == 'notice' %>

    <div class="text-center alert alert-<%= css_class %>">
      <%= message.html_safe %>
    </div>
  <% end %>
</div>

app/views/shared/_game.html.erb
<%# cache(game, expires_in: 1.hour) do %>
  <div class="game col-md-3">
    <div class="round-name">
      <%= game.round_name %>
    </div>
    <div class="start-time">
      <% if game.start_time %>
        <%= game.start_time.strftime('%b. %-d, %l:%M%P') %>
      <% else %>
        Start Time TBD
    <% end %>
    </div>

    <div class="team-one">
      <%= link_to game.school1.full_name, school_path(game.school1) %>
      <%= game.try(:school1_score) %>
    </div>

    <% if game.school2 %>
      <div class="team-two">
        <%= link_to game.school2.full_name, school_path(game.school2) %>
        <%= game.try(:school2_score) %>
      </div>
    <% end %>
  </div>
<%# end %>

app/views/shared/_header.html.erb
<nav id="dm-header" class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <div class="navbar-brand">
        <%= image_tag 'bball-icon.png', class: 'img-responsive bball-icon' %>
      </div>
    </div>

    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="title active">
          <% title_path = user_signed_in? ? user_path(current_user) : root_path %>
          <%= link_to "Madness Draft #{Date.today.year}", title_path %>
        </li>
        <li>
          <%= link_to 'Rules', rules_path %>
        </li>
        <li>
          <%= link_to 'Contact', contact_path %>
        </li>
        <li>
          <%= link_to 'Privacy', privacy_path %>
        </li>
        <% if current_user.try(:admin?) %>
          <li>
            <%= link_to 'Update Games', admin_games_path %>
          </li>
        <% end %>
      </ul>

      <% if user_signed_in? %>
        <div class="logout">
          <%= link_to 'Log Out', logout_path, class: 'btn' %>
        </div>
      <% elsif action_name != 'new' %>
        <div class="logout">
          <%= link_to 'Log In', new_user_session_path, class: 'btn' %>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_points.html.erb
<% cache 'points_board', expires_in: 6.hours do %>
  <div class="row">

    <h3>Possible Points</h3>
    <h4>The amount of points a team of each seed could win in each round</h4>

    <table class="table table-responsive table-hover table-condensed">
      <tr class="active">
        <th>Seed</th>
        <% 6.times do |round| %>
          <th><%= Game::ROUND_NAMES[round] %></th>
        <% end %>
        <th>Max</th>
      </tr>
      <% (1..16).to_a.each do |seed_number| %>
        <tr>
          <th><%= seed_number %></th>
          <% 6.times do |round| %>
            <td><%= Seed.points_for_winning(seed_number, round) %></td>
          <% end %>
          <td><%= Seed.points_for_winning_it_all(seed_number) %></td>
        </tr>
      <% end %>
    </table>
  </div>
<% end %>